/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alumni_202557201020;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author ASUS
 */
public class frameDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frameDashboard.class.getName());
    private CardLayout cardLayout;
    /**
     * Creates new form frameDashboard
     */
    public frameDashboard() {
        initComponents();
        
        inisiasiPanel();
    }
    
    void inisiasiPanel(){
        cardLayout = (CardLayout)panelContent.getLayout();
        
        panelContent.add(new panelDashboard(), "dashboard");
        panelContent.add(new paneljurusan(), "jurusan");
        panelContent.add(new panelGuru(), "guru");
        panelContent.add(new panelKelas(), "kelas");
        panelContent.add(new panelSiswa(), "siswa");
        panelContent.add(new panelAbout(), "about");
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        panelButton = new javax.swing.JPanel();
        bDasbor = new javax.swing.JButton();
        bJurusan = new javax.swing.JButton();
        bGuru = new javax.swing.JButton();
        bKelas = new javax.swing.JButton();
        bSiswa = new javax.swing.JButton();
        bAbout = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        lAloomni = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lKeluar = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSidebar.setBackground(new java.awt.Color(68, 130, 251));
        panelSidebar.setMaximumSize(new java.awt.Dimension(200, 32767));
        panelSidebar.setMinimumSize(new java.awt.Dimension(200, 0));
        panelSidebar.setPreferredSize(new java.awt.Dimension(250, 600));

        panelButton.setBackground(new java.awt.Color(68, 130, 251));
        panelButton.setLayout(new java.awt.GridLayout(0, 1, 0, 7));

        bDasbor.setBackground(new java.awt.Color(68, 130, 251));
        bDasbor.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        bDasbor.setForeground(new java.awt.Color(255, 255, 255));
        bDasbor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201020/img/uiw_dashboard.png"))); // NOI18N
        bDasbor.setText("Dasbor");
        bDasbor.setBorderPainted(false);
        bDasbor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bDasbor.setIconTextGap(10);
        bDasbor.addActionListener(this::bDasborActionPerformed);
        panelButton.add(bDasbor);

        bJurusan.setBackground(new java.awt.Color(68, 130, 251));
        bJurusan.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        bJurusan.setForeground(new java.awt.Color(255, 255, 255));
        bJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201020/img/lucide_university.png"))); // NOI18N
        bJurusan.setText("Jurusan");
        bJurusan.setBorderPainted(false);
        bJurusan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bJurusan.setIconTextGap(10);
        bJurusan.addActionListener(this::bJurusanActionPerformed);
        panelButton.add(bJurusan);

        bGuru.setBackground(new java.awt.Color(68, 130, 251));
        bGuru.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        bGuru.setForeground(new java.awt.Color(255, 255, 255));
        bGuru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201020/img/tabler_chalkboard-teacher.png"))); // NOI18N
        bGuru.setText("Guru");
        bGuru.setBorderPainted(false);
        bGuru.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bGuru.setIconTextGap(10);
        bGuru.addActionListener(this::bGuruActionPerformed);
        panelButton.add(bGuru);

        bKelas.setBackground(new java.awt.Color(68, 130, 251));
        bKelas.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        bKelas.setForeground(new java.awt.Color(255, 255, 255));
        bKelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201020/img/arcticons_classroom.png"))); // NOI18N
        bKelas.setText("Kelas");
        bKelas.setBorderPainted(false);
        bKelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bKelas.setIconTextGap(10);
        bKelas.addActionListener(this::bKelasActionPerformed);
        panelButton.add(bKelas);

        bSiswa.setBackground(new java.awt.Color(68, 130, 251));
        bSiswa.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        bSiswa.setForeground(new java.awt.Color(255, 255, 255));
        bSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201020/img/radix-icons_person.png"))); // NOI18N
        bSiswa.setText("Siswa");
        bSiswa.setBorderPainted(false);
        bSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bSiswa.setIconTextGap(10);
        bSiswa.addActionListener(this::bSiswaActionPerformed);
        panelButton.add(bSiswa);

        bAbout.setBackground(new java.awt.Color(68, 130, 251));
        bAbout.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        bAbout.setForeground(new java.awt.Color(255, 255, 255));
        bAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201020/img/ix_about (3).png"))); // NOI18N
        bAbout.setText("About");
        bAbout.setBorderPainted(false);
        bAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bAbout.setIconTextGap(10);
        bAbout.addActionListener(this::bAboutActionPerformed);
        panelButton.add(bAbout);

        bLogout.setBackground(new java.awt.Color(68, 130, 251));
        bLogout.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        bLogout.setForeground(new java.awt.Color(255, 255, 255));
        bLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201020/img/mdi_logout.png"))); // NOI18N
        bLogout.setText("Logout");
        bLogout.setBorderPainted(false);
        bLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bLogout.setIconTextGap(10);
        bLogout.addActionListener(this::bLogoutActionPerformed);
        panelButton.add(bLogout);

        lAloomni.setFont(new java.awt.Font("Poppins ExtraBold", 0, 24)); // NOI18N
        lAloomni.setForeground(new java.awt.Color(255, 255, 255));
        lAloomni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201020/img/ri_graduation-cap-fill.png"))); // NOI18N
        lAloomni.setText("Aloomni");
        lAloomni.setIconTextGap(7);

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lAloomni, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lAloomni)
                .addGap(61, 61, 61)
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        getContentPane().add(panelSidebar, java.awt.BorderLayout.LINE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 35));

        lKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201020/img/icons8-close-20.png"))); // NOI18N
        lKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lKeluarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(676, Short.MAX_VALUE)
                .addComponent(lKeluar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(lKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setLayout(new java.awt.CardLayout());
        jPanel1.add(panelContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lKeluarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lKeluarMouseClicked

    private void bDasborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDasborActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "dashboard");
    }//GEN-LAST:event_bDasborActionPerformed

    private void bJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJurusanActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "jurusan");
    }//GEN-LAST:event_bJurusanActionPerformed

    private void bGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuruActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "guru");
    }//GEN-LAST:event_bGuruActionPerformed

    private void bKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKelasActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "kelas");
    }//GEN-LAST:event_bKelasActionPerformed

    private void bSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiswaActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "siswa");
    }//GEN-LAST:event_bSiswaActionPerformed

    private void bAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAboutActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "about");
    }//GEN-LAST:event_bAboutActionPerformed

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(
                null,
                "Apakah anda yakin ingin keluar",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        
        switch (pilihan){
            case JOptionPane.YES_OPTION:
                dispose();
                new frameLogin().setVisible(true);
                break;
            case JOptionPane.NO_OPTION:
                break;
            default:
                break;
        }
    }//GEN-LAST:event_bLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.put("Button.arc", 10);
            UIManager.put("Button.borderwidht", 0);
            UIManager.put("TextComponent.arc", 10);
            UIManager.put("Component.borderwidht", 0);
            UIManager.put("Component.focusWidth", 0);
            UIManager.put("Component.innerFocuswidht", 0);
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException e) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frameDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbout;
    private javax.swing.JButton bDasbor;
    private javax.swing.JButton bGuru;
    private javax.swing.JButton bJurusan;
    private javax.swing.JButton bKelas;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bSiswa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lAloomni;
    private javax.swing.JLabel lKeluar;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables

}
