/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni_202557201020;

import alumni_202557201020.config.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class paneljurusan extends javax.swing.JPanel {

    /**
     * Creates new form paneljurusan
     */
    public paneljurusan() {
        initComponents();
        
        //memanggil method reset dan load_tabel_jurusan
        reset();
        
        load_tabel_jurusan();
    }
    
    //membuat method reset
    void reset(){
        //kosongkan isi text field kode jurusan
        tKodeJurusan.setText(null);
        
        //aktifkan kembali text field kode jurusan agar bisa diedit
        tKodeJurusan.setEditable(true);
        
        //kosongkan isi text field nama jurusan
        tNamaJurusan.setText(null);
    }
    
    
    //membuat method untuk menampilkan data jurusan
    void load_tabel_jurusan(){
        //membuat objek model tabel baru
        DefaultTableModel model = new DefaultTableModel();
        
        //Menambahkan kolom ke dalam model table
        
        //Kolom pertama untuk kode jurusan
        model.addColumn("Kode Jurusan");
        //Kolom kedua untuk nama jurusan
        model.addColumn("Nama Jurusan");
        
        //Query SQL untuk mengambil semua data dari tabel jurusan
        String sql = "SELECT * FROM jurusan";
        
        try {
            //Membuka koneksi ke database
            Connection conn = koneksi.konek();

            //membuat statement untuk menjalankan query
            Statement st = conn.createStatement();

            //menjalankan query dan meninyimpan hasilnya dalam ResultSet
            ResultSet rs = st.executeQuery(sql);

            //melakukan iterasi untuk setiap baris data hasil query
            while (rs.next()) {
                //mengambil data kolom kode jur
                String kodeJurusan = rs.getString("kode_jur");

                //mengambil data kolom nama jurusan
                String namaJurusan = rs.getString("nama_jur");

                //membuat array berisi data satu baris
                Object[] baris = {kodeJurusan, namaJurusan};

                //menambahkan array baris ke dalam model table
                model.addRow(baris);
            }
        } catch (SQLException sQLException) {
            //menampilkan pesan error jika gagal mengambil data dari database
            JOptionPane.showMessageDialog(null, "Gagal mengambil data!");
        }
        //menampilkan model yang sudah diisi kedalam tabel GUI
        tblJurusan.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        tKodeJurusan = new javax.swing.JTextField();
        tNamaJurusan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJurusan = new javax.swing.JTable();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 20, true));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(68, 130, 251));
        jPanel1.setPreferredSize(new java.awt.Dimension(598, 60));

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Jurusan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(613, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(695, 180));

        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        btnTambah.setBackground(new java.awt.Color(0, 181, 53));
        btnTambah.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201020/img/typcn_plus.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);
        jPanel4.add(btnTambah);

        btnUbah.setBackground(new java.awt.Color(255, 153, 0));
        btnUbah.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201020/img/mdi_edit.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(this::btnUbahActionPerformed);
        jPanel4.add(btnUbah);

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201020/img/material-symbols_delete-rounded (1).png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        jPanel4.add(btnHapus);

        btnReset.setBackground(new java.awt.Color(58, 153, 250));
        btnReset.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201020/img/ri_reset-left-fill.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);
        jPanel4.add(btnReset);

        tKodeJurusan.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N

        tNamaJurusan.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel1.setText("Kode Jurusan");

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel3.setText("Nama Jurusan");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tKodeJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNamaJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tKodeJurusan, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(tNamaJurusan))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 20, 20, 20, new java.awt.Color(242, 242, 242)));
        jPanel5.setLayout(new java.awt.BorderLayout());

        tblJurusan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblJurusan.setRowHeight(40);
        tblJurusan.setShowGrid(false);
        tblJurusan.setShowHorizontalLines(true);
        tblJurusan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJurusanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblJurusan);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblJurusanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJurusanMouseClicked
        // TODO add your handling code here:
        //Ambil indeks baris yang diklik oleh pengguna ditabel tblJurusan
        int barisYangDipilih = tblJurusan.rowAtPoint(evt.getPoint());
        
        //Ambil nilai dari kolom pertama (indeks 0) pada baris yang dipilih yaitu kode_jur
        String kodeJurusan = tblJurusan.getValueAt(barisYangDipilih, 0).toString();
        
         //Ambil nilai dari kolom pertama (indeks 1) pada baris yang dipilih yaitu nama_jur
        String namaJurusan = tblJurusan.getValueAt(barisYangDipilih, 1).toString();
        
        //Tampilkan kode jurusan ditext field tkodeJurusan
        tKodeJurusan.setText(kodeJurusan);
        
        //menonaktifkan pengeditan pada text field kode jurusan (agar tidak bisa diubah
        tKodeJurusan.setEditable(false);
        
        //tampilkan nama jurusan di text field tnamaJurusan
        tNamaJurusan.setText(namaJurusan);
    }//GEN-LAST:event_tblJurusanMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        //Ambil input dari text field tKodeJurusan dan simpan ke variabel tKodeJurusan
        String kodeJurusan = tKodeJurusan.getText();

        //Ambil input dari text field  tNamaJurusan dan simpan ke variabel tNamaJurusan
        String namaJurusan = tNamaJurusan.getText();

        //Query SQL untuk menyisipkan data ke tabel jurusan
        String sql = "INSERT INTO jurusan(kode_jur, nama_jur) VALUES(?,?)";

        try {
            //Buat koneksi ke database menggunakan method koneksi() dari class koneksi
            Connection conn = koneksi.konek();

            //Siapkan query SQL untuk dieksekusi dengan parameter
            PreparedStatement ps = conn.prepareStatement(sql);

            //Isi parameter pertama(?) dengan kode jurusan
            ps.setString(1, kodeJurusan);

            //Isi parameter kedua(?) dengan nama jurusan
            ps.setString(2, namaJurusan);

            //Jalankan query untuk menyimpan data ke database
            ps.execute();

            //Tampilkan pesan bahwa data berhasil disimpan
            JOptionPane.showInternalMessageDialog(null, "Data berhasil disimpan");
        } catch (SQLException sQLException) {
            //jika terjadi kesalahan saat menyimpan data, tampilkan pesan
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        }
        //panggil method untuk memuat ulang data pada tabel jurusan
        load_tabel_jurusan();
        
        //panggil method untuk mereset atau mengosongkan inputan
        reset();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        //Ambil input dari text field tKodeJurusan dan simpan ke variabel tKodeJurusan
        String kodeJurusan = tKodeJurusan.getText();

        //Ambil input dari text field  tNamaJurusan dan simpan ke variabel tNamaJurusan
        String namaJurusan = tNamaJurusan.getText();

        //Query SQL untuk mengubah data pada tabel jurusan
        String sql = "UPDATE jurusan SET nama_jur=? WHERE kode_jur=?";
        
        try {
            //Buat koneksi ke database menggunakan method koneksi() dari class koneksi
            Connection conn = koneksi.konek();

            //Siapkan query SQL untuk dieksekusi dengan parameter
            PreparedStatement ps = conn.prepareStatement(sql);

            //Isi parameter pertama(?) dengan kode jurusan
            ps.setString(1, namaJurusan);

            //Isi parameter kedua(?) dengan nama jurusan
            ps.setString(2, kodeJurusan);

            //Jalankan query untuk menyimpan data ke database
            ps.execute();

            //Tampilkan pesan bahwa data berhasil diubah
            JOptionPane.showInternalMessageDialog(null, "Data berhasil diubah");
        } catch (SQLException sQLException) {
            //jika terjadi kesalahan saat mengubah data, tampilkan pesan
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }
        //panggil method untuk memuat ulang data pada tabel jurusan
        load_tabel_jurusan();
        
        //panggil method untuk mereset atau mengosongkan inputan
        reset();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        //Ambil input dari text field tKodeJurusan dan simpan ke variabel tKodeJurusan
        String kodeJurusan = tKodeJurusan.getText();
        
        //Query SQL untuk menghapus data pada tabel jurusan berdasarkan kode_jur
        String sql = "DELETE FROM jurusan WHERE kode_jur=?";
        
        try {
            //Buat koneksi ke database menggunakan method koneksi() dari class koneksi
            Connection conn = koneksi.konek();

            //Siapkan query SQL untuk dieksekusi dengan parameter
            PreparedStatement ps = conn.prepareStatement(sql);

            //Isi parameter pertama(?) dengan kode jurusan
            ps.setString(1, kodeJurusan);

            //Jalankan query untuk menyimpan data ke database
            ps.execute();

            //Tampilkan pesan bahwa data berhasil diubah
            JOptionPane.showInternalMessageDialog(null, "Data berhasil dihapus");
        } catch (SQLException sQLException) {
            //jika terjadi kesalahan saat mengubah data, tampilkan pesan
            JOptionPane.showMessageDialog(null, "Data gagal dihapus");
        }
        //panggil method untuk memuat ulang data pada tabel jurusan
        load_tabel_jurusan();
        
        //panggil method untuk mereset atau mengosongkan inputan
        reset();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tKodeJurusan;
    private javax.swing.JTextField tNamaJurusan;
    private javax.swing.JTable tblJurusan;
    // End of variables declaration//GEN-END:variables
}
