/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni_202557201020;

import alumni_202557201020.config.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class panelGuru extends javax.swing.JPanel {

    /**
     * Creates new form panelGuru
     */
    public panelGuru() {
        initComponents();
        
        //mengosongkan form input dan mengatur ulang komponen imput
        reset();
        
        //memuat data dari database ke dalam tabel guru pada GUI
        load_tabel_guru();
    }
    
    //membuat method reset
    void reset(){
        //kosongkan isi text field NIP
        tNIP.setText(null);
        
        //aktifkan kembali text field NIP agar bisa diedit
        tNIP.setEditable(true);
        
        //kosongkan isi text field nama guru
        tNamaGuru.setText(null);
        
        //reset pilihan jenis kelamin(combo box)
        cJK.setSelectedItem(null);
        
        //kosongkan field alamat
        tAlamat.setText(null);
    }
    
    //membuat method untuk menampilkan data jurusan
    void load_tabel_guru(){
        //membuat objek model tabel baru
        DefaultTableModel model = new DefaultTableModel();
        
        //Menambahkan kolom ke dalam model table
        model.addColumn("NIP");
        model.addColumn("Nama Guru");
        model.addColumn("L/P");
        model.addColumn("Alamat");
        
        //Query SQL untuk mengambil semua data dari tabel jurusan
        String sql = "SELECT * FROM guru";
        
        try {
            //Membuka koneksi ke database
            Connection conn = koneksi.konek();

            //membuat statement untuk menjalankan query
            Statement st = conn.createStatement();

            //menjalankan query dan meninyimpan hasilnya dalam ResultSet
            ResultSet rs = st.executeQuery(sql);

            //melakukan iterasi untuk setiap baris data hasil query
            while (rs.next()) {
                //mengambil nilai dari masing" kolom
                String NIP = rs.getString("nip");
                String namaGuru = rs.getString("nama_guru");
                String JK = rs.getString("gender");
                String alamat = rs.getString("alamat");
                
                //menyusun data kedalam array objek
                Object[] baris = {NIP, namaGuru, JK, alamat};

                //menambahkan array baris ke dalam model table
                model.addRow(baris);
            }
        } catch (SQLException sQLException) {
            //menampilkan pesan error jika gagal mengambil data dari database
            JOptionPane.showMessageDialog(null, "Gagal mengambil data!");
        }
        //menampilkan model yang sudah diisi kedalam tabel GUI
        tblGuru.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tNIP = new javax.swing.JTextField();
        tNamaGuru = new javax.swing.JTextField();
        cJK = new javax.swing.JComboBox<>();
        tAlamat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGuru = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        setPreferredSize(new java.awt.Dimension(976, 620));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(68, 130, 251));
        jPanel1.setPreferredSize(new java.awt.Dimension(733, 60));

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Guru");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(855, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(936, 520));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 469));

        tNIP.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        tNamaGuru.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        cJK.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));

        tAlamat.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel1.setText("NIP");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Alamat");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tNamaGuru)
                        .addComponent(tNIP)
                        .addComponent(cJK, 0, 366, Short.MAX_VALUE)
                        .addComponent(tAlamat)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNamaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cJK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(30, 20, 1, 20, new java.awt.Color(242, 242, 242)));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(496, 80));

        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        btnTambah.setBackground(new java.awt.Color(0, 181, 53));
        btnTambah.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201020/img/typcn_plus.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);
        jPanel6.add(btnTambah);

        btnUbah.setBackground(new java.awt.Color(255, 153, 0));
        btnUbah.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201020/img/mdi_edit.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(this::btnUbahActionPerformed);
        jPanel6.add(btnUbah);

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201020/img/material-symbols_delete-rounded (1).png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        jPanel6.add(btnHapus);

        btnReset.setBackground(new java.awt.Color(58, 153, 250));
        btnReset.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201020/img/ri_reset-left-fill.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);
        jPanel6.add(btnReset);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        tblGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblGuru.setRowHeight(35);
        tblGuru.setShowHorizontalLines(true);
        tblGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGuruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGuru);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGuruMouseClicked
        // TODO add your handling code here:
        //Ambil indeks baris yang diklik oleh pengguna ditabel tblJurusan
        int barisYangDipilih = tblGuru.rowAtPoint(evt.getPoint());
        
        //Ambil nilai baris yang dipilih pada tabel guru
        String NIP = tblGuru.getValueAt(barisYangDipilih, 0).toString();
        String namaGuru = tblGuru.getValueAt(barisYangDipilih, 1).toString();
        
        // Mengambil objek dari kolom ketiga (Jenis Kelamin)
        Object jkObj = tblGuru.getValueAt(barisYangDipilih, 2);
        
        // Mengambil objek dari kolom keempat (alamat)
        Object alamatObj = tblGuru.getValueAt(barisYangDipilih, 3);
        
        String JK = (jkObj != null) ? jkObj.toString() : "";
        String alamat = (alamatObj != null) ? alamatObj.toString() : "";
        
        //Tampilkan nip ditext field tNIP
        tNIP.setText(NIP);
        
        //menonaktifkan pengeditan pada text field tNIP(agar tidak bisa diubah
        tNIP.setEditable(false);
        
        //tampilkan nama jurusan di text field tnamaJurusan
        tNamaGuru.setText(namaGuru);
        
        //tampilkan nama alamat di text field tAlamat
        tAlamat.setText(alamat);
        
        //Mengecek isi nilai jenis kelamin dan menyesuaikan pilihan pada combo box CJK
        switch (JK){
            //jika nilai JK "L", set pilihan combo box ke "laki-laki"
            case "L":
                cJK.setSelectedItem("Laki-Laki");
                break;
                
            //jika nilai JK "P", set pilihan combo box ke "perempuan"
            case "P":
                cJK.setSelectedItem("Perempuan");
                break;
                
            //jika nilainya buka "L" atau "P", kosongkan pilihan combo box
            default:
                cJK.setSelectedItem(null);
                break;
        }
    }//GEN-LAST:event_tblGuruMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        //Ambil input dari text field dan combo box pada GUI
        String NIP = tNIP.getText();
        String namaGuru = tNamaGuru.getText();
        String JK = cJK.getSelectedItem().toString();
        String alamat = tAlamat.getText();
        
        //menyiapkan variabel j_k (jeniskelamin dalam format singkatan "L" atau "P" 
        String j_k = null;
        
        //mengubah nilai JK dari lanel menjadi format singkatan yang disimpan di database
        switch (JK){
            case "Laki-Laki":
                j_k = "L";
                break;
            case "Perempuan":
                j_k = "P";
                break;
            default:
                j_k = "null";
                break;
        }

        //Query SQL untuk menyisipkan data ke tabel jurusan
        String sql = "INSERT INTO guru(NIP, nama_guru, gender, alamat) VALUES(?,?,?,?)";

        try {
            //Buat koneksi ke database menggunakan method koneksi() dari class koneksi
            Connection conn = koneksi.konek();

            //Siapkan query SQL untuk dieksekusi dengan parameter
            PreparedStatement ps = conn.prepareStatement(sql);

            //Isi parameter
            ps.setString(1, NIP);
            ps.setString(2, namaGuru);
            ps.setString(3, j_k);
            ps.setString(4, alamat);

            //Jalankan query untuk menyimpan data ke database
            ps.execute();

            //Tampilkan pesan bahwa data berhasil disimpan
            JOptionPane.showInternalMessageDialog(null, "Data berhasil disimpan");
        } catch (SQLException sQLException) {
            //jika terjadi kesalahan saat menyimpan data, tampilkan pesan
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        }
        //panggil method untuk memuat ulang data pada tabel guru
        load_tabel_guru();
        
        //panggil method untuk mereset atau mengosongkan inputan
        reset();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        //Ambil input dari text field dan combo box pada GUI
        String NIP = tNIP.getText();
        String namaGuru = tNamaGuru.getText();
        String JK = cJK.getSelectedItem().toString();
        String alamat = tAlamat.getText();

        //menyiapkan variabel j_k (jeniskelamin dalam format singkatan "L" atau "P" 
        String j_k = null;
        
        //mengubah nilai JK dari lanel menjadi format singkatan yang disimpan di database
        switch (JK){
            case "Laki-Laki":
                j_k = "L";
                break;
            case "Perempuan":
                j_k = "P";
                break;
            default:
                j_k = "null";
                break;
        }
        
        //Query SQL untuk mengubah data pada tabel jurusan
        String sql = "UPDATE guru SET nama_guru=? WHERE nip=?";
        
        try {
            //Buat koneksi ke database menggunakan method koneksi() dari class koneksi
            Connection conn = koneksi.konek();

            //Siapkan query SQL untuk dieksekusi dengan parameter
            PreparedStatement ps = conn.prepareStatement(sql);

            //Isi parameter
            ps.setString(1, NIP);
            ps.setString(2, namaGuru);
            ps.setString(3, j_k);
            ps.setString(4, alamat);

            //Jalankan query untuk menyimpan data ke database
            ps.execute();

            //Tampilkan pesan bahwa data berhasil diubah
            JOptionPane.showInternalMessageDialog(null, "Data berhasil diubah");
        } catch (SQLException sQLException) {
            //jika terjadi kesalahan saat mengubah data, tampilkan pesan
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }
        //panggil method untuk memuat ulang data pada tabel guru
        load_tabel_guru();
        
        //panggil method untuk mereset atau mengosongkan inputan
        reset();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        //Ambil input dari text field tKodeJurusan dan simpan ke variabel tKodeJurusan
        String NIP = tNIP.getText();
        
        //Query SQL untuk menghapus data pada tabel guru berdasarkan NIP
        String sql = "DELETE FROM guru WHERE nip=?";
        
        try {
            //Buat koneksi ke database menggunakan method koneksi() dari class koneksi
            Connection conn = koneksi.konek();

            //Siapkan query SQL untuk dieksekusi dengan parameter
            PreparedStatement ps = conn.prepareStatement(sql);

            //Isi parameter pertama(?) dengan kode jurusan
            ps.setString(1, NIP);

            //Jalankan query untuk menyimpan data ke database
            ps.execute();

            //Tampilkan pesan bahwa data berhasil dihapus
            JOptionPane.showInternalMessageDialog(null, "Data berhasil dihapus");
        } catch (SQLException sQLException) {
            //jika terjadi kesalahan saat mengubah data, tampilkan pesan
            JOptionPane.showMessageDialog(null, "Data gagal dihapus");
        }
        //panggil method untuk memuat ulang data pada tabel guru
        load_tabel_guru();
        
        //panggil method untuk mereset atau mengosongkan inputan
        reset();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cJK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tNIP;
    private javax.swing.JTextField tNamaGuru;
    private javax.swing.JTable tblGuru;
    // End of variables declaration//GEN-END:variables
}
