/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni_202557201020;

import alumni_202557201020.config.koneksi;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;

/**
 *
 * @author ASUS
 */
public class panelDashboard extends javax.swing.JPanel {

    /**
     * Creates new form panelDashboard
     */
    public panelDashboard() {
        initComponents();
        
        isiJumlahDataDasbor();
    }
    
    private void isiJumlahDataDasbor() {

    // Membuka koneksi ke database
    Connection conn = koneksi.konek();

    try {

        // Mengambil jumlah data jurusan dari tabel jurusan
        String sqlJurusan = "SELECT COUNT(*) AS jumlah FROM jurusan";
        Statement psJurusan = conn.createStatement();
        ResultSet rsJurusan = psJurusan.executeQuery(sqlJurusan);

        // Jika hasil query tersedia, ambil nilai jumlah dan tampilkan pada label jumlah jurusan
        if (rsJurusan.next()) {
            int jumlah = rsJurusan.getInt("jumlah");
            tJumlahJurusan.setText(String.valueOf(jumlah));
        }

        // Mengambil jumlah data guru dari tabel guru
        String sqlGuru = "SELECT COUNT(*) AS jumlah FROM guru";
        Statement psGuru = conn.createStatement();
        ResultSet rsGuru = psGuru.executeQuery(sqlGuru);

        // Jika hasil query tersedia, ambil nilai jumlah dan tampilkan pada label jumlah guru
        if (rsGuru.next()) {
            int jumlah = rsGuru.getInt("jumlah");
            tJumlahGuru.setText(String.valueOf(jumlah));
        }

        // Mengambil jumlah data siswa dari tabel siswa
        String sqlSiswa = "SELECT COUNT(*) AS jumlah FROM siswa";
        Statement psSiswa = conn.createStatement();
        ResultSet rsSiswa = psSiswa.executeQuery(sqlSiswa);

        // Jika hasil query tersedia, ambil nilai jumlah dan tampilkan pada label jumlah siswa
        if (rsSiswa.next()) {
            int jumlah = rsSiswa.getInt("jumlah");
            tJumlahSiswa.setText(String.valueOf(jumlah));
        }

        // Mengambil jumlah data kelas dari tabel kelas
        String sqlKelas = "SELECT COUNT(*) AS jumlah FROM kelas";
        Statement psKelas = conn.createStatement();
        ResultSet rsKelas = psKelas.executeQuery(sqlKelas);

        // Jika hasil query tersedia, ambil nilai jumlah dan tampilkan pada label jumlah kelas
        if (rsKelas.next()) {
            int jumlah = rsKelas.getInt("jumlah");
            tJumlahKelas.setText(String.valueOf(jumlah));
        }

    } catch (SQLException e) {

        // Menampilkan pesan pada konsol jika terjadi kesalahan saat mengambil data
        System.err.println("Gagal mengambil jumlah data");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tJumlahJurusan = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tJumlahGuru = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tJumlahSiswa = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tJumlahKelas = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 20, true));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 20, 1, 20, new java.awt.Color(242, 242, 242)));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(650, 150));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(68, 130, 251));
        jPanel4.setPreferredSize(new java.awt.Dimension(650, 30));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(68, 130, 251));
        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Jumlah Jurusan");
        jPanel4.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        tJumlahJurusan.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        tJumlahJurusan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tJumlahJurusan.setText("JJ");
        jPanel3.add(tJumlahJurusan, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel2);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(650, 150));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(68, 130, 251));
        jPanel7.setPreferredSize(new java.awt.Dimension(650, 30));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(68, 130, 251));
        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jumlah Guru");
        jPanel7.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        tJumlahGuru.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        tJumlahGuru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tJumlahGuru.setText("JG");
        jPanel6.add(tJumlahGuru, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel5);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(650, 150));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(68, 130, 251));
        jPanel10.setPreferredSize(new java.awt.Dimension(650, 30));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel4.setBackground(new java.awt.Color(68, 130, 251));
        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Jumlah Siswa");
        jPanel10.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        tJumlahSiswa.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        tJumlahSiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tJumlahSiswa.setText("JK");
        jPanel9.add(tJumlahSiswa, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel8);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(650, 150));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(new java.awt.Color(68, 130, 251));
        jPanel13.setPreferredSize(new java.awt.Dimension(650, 30));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel5.setBackground(new java.awt.Color(68, 130, 251));
        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jumlah Kelas");
        jPanel13.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        tJumlahKelas.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        tJumlahKelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tJumlahKelas.setText("JS");
        jPanel12.add(tJumlahKelas, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel11);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel tJumlahGuru;
    private javax.swing.JLabel tJumlahJurusan;
    private javax.swing.JLabel tJumlahKelas;
    private javax.swing.JLabel tJumlahSiswa;
    // End of variables declaration//GEN-END:variables
}
